(test
 (name test)
 (libraries irmin alcotest eio_main))

(test
 (name test_stm)
 (modules test_stm)
 (libraries irmin irmin-lavyek eio_main qcheck-core qcheck-stm.stm
            qcheck-stm.sequential qcheck-stm.domain qcheck-stm-eio.domain))

(executable
 (name mst_proof)
 (modules mst_proof)
 (libraries irmin))

(cram
 (package irmin)
 (applies_to cli)
 (deps %{bin:irmin}))

(cram
 (package irmin)
 (applies_to proof)
 (deps mst_proof.exe))
